#!/bin/bash
#####
# HoroBot compiler/runner
####
INPUT='script.coffee'
OUTPUT='bot.js'
DEBUGFILE='debug.txt'

echo 'Compiling HoroBot'
coffee --print ${INPUT} > ${OUTPUT}
echo 'Done'
echo 'Running program'
node ${OUTPUT} | tee -a ${DEBUGFILE}
